project_id = "xlwoystgrwonzyhwuxxl"

[functions.admin-auth]
verify_jwt = false

[functions.admin-teams]
verify_jwt = false

[functions.admin-hackathons]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.delete-user-completely]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false