// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlwoystgrwonzyhwuxxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsd295c3Rncndvbnp5aHd1eHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzc0NjIsImV4cCI6MjA3MjkxMzQ2Mn0.NsXCKTMph6NpHPl9IBqwxrg2cIT1W-qMMDWNiupUU2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});